### coffee
layout: "default"
title: "Document Title"
description: "<p style=\"margin-bottom: 10px; border-style: initial; border-color: initial; outline-width: 0px; outline-style: initial; outline-color: initial; vertical-align: baseline; background-image: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: rgb(0, 0, 0); font-family: arial; line-height: normal; \">Ut lectus et montes lundium! Sociis turpis lacus, mid magna turpis scelerisque, augue tristique, tristique urna magna pulvinar in aenean, mattis sed dictumst aliquet. Auctor. Nisi vel magnis nec porttitor platea adipiscing ac rhoncus vel sed, elementum risus sit nisi? Porta porttitor lectus habitasse? Placerat dis aenean in, auctor magna elementum turpis, rhoncus dapibus in vel. Egestas sit. Aenean integer, cursus et, tortor magna, mattis augue vut purus tempor mattis et non pellentesque cursus mid quis porta placerat, magna ridiculus etiam! Ultrices non urna? Arcu penatibus, est! Ut enim habitasse integer mattis turpis sociis! Porttitor augue montes dis est pulvinar! Scelerisque montes! Augue urna! Egestas nisi? Lacus et nisi in. Dapibus a diam dis, aenean purus, sagittis! Augue, turpis lundium.</p><p style=\"margin-bottom: 10px; border-style: initial; border-color: initial; outline-width: 0px; outline-style: initial; outline-color: initial; vertical-align: baseline; background-image: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: rgb(0, 0, 0); font-family: arial; line-height: normal; \">Tortor urna ac, scelerisque? Ut! Nisi montes sed nunc. Lorem nisi et in eros diam arcu rhoncus tincidunt etiam sagittis vut. Tristique integer amet. Mattis et. Lectus pellentesque egestas nunc porta dapibus ac enim, nunc, enim ut cras, duis ut pellentesque? Ultrices ac turpis sit odio, proin, augue turpis augue sociis vel turpis, tristique est cursus non ac ultricies! A velit a turpis. Turpis sed sagittis in placerat auctor ac magnis, dolor magna velit elit, et facilisis ac et, in pulvinar tristique elementum! Hac magnis vut lacus a cras porta turpis, pid ut cursus et nascetur odio est aenean, mid elementum, porttitor et. Cursus, lacus tempor penatibus, odio cum! Amet, penatibus integer odio lorem pulvinar enim vut scelerisque porta.</p>\n  \n  \n  \n  "
###

article 'typeof': 'sioc:Post', about: @document.url, ->
    h1 property: 'title', -> @document.title
    div property: 'description', -> @document.description
